// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Demo(Props) {
  return React.createElement("h1", undefined, "Hello World");
}

var make = Demo;

export {
  make ,
  
}
/* react Not a pure module */
